id: IE187BE33
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T10:25:26+00:00'
last_modified: '2022-06-08T07:37:44.482060+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29341
  title: ངེས་དོན་ཕྱག་རྒྱ་ཆེན་པོའི་སྒོམ་རིམ་གསལ་བར་བྱེད་པ་ལེགས་བཤད་ཟླ་བའི་འོད་ཟེར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5F8B:
      image_group_id: I5275
      title: ''
      total_pages: 906
      order: 1
      base_file: 5F8B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
